name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build with Wails
        run: wails build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/bin/*.exe
          generate_release_notes: true